### ISSUE TITLE
Is it possible to use async Redis connection pool with Pyrate-limiter?

### ISSUE THREAD

**Issue by drygdryg** [vutran1710/PyrateLimiter#105]
I found that Pyrate-limiter uses a synchronous Redis connection under the hood, even for [asynchronous ratelimiter decorator](https://pyratelimiter.readthedocs.io/en/latest/#async-decorator-contextmanager).
Is it possible to use async Redis connection pool with Pyrate-limiter and is there any performance-related reasons for using asynchronous Redis connection in a fully asynchronous application?

**Comment by vutran1710** [comment]
the problem with asynchronosity is it's... asynchronous - meaning context switching, job switching, and most of the time you wont know  the time it takes for a concurrency task to complete.

Lets say you are sending a timeframe data using 'now()' to redis, think about what time exactly - in reality - the redis server will receive it?

- in synchronous context, it will be 'now() + network_latency'. network latency is already quite unpredictable by nature.

- in asynchronous, it will be 'now() + any-concurrent-blocking task? + latency + some-more-concurrent-task + the-limiter-proceeding-logic' - and by time we reach the proceeding logic, the limiter state might already be badly tampered by the slippage of time.

from my understanding, thats not nice and not easy to handle.

feel free to correct me if im wrong. thanks

**Comment by vutran1710** [comment]
Resolved in the new major release!
