### ISSUE TITLE
Exceeded RequestRate Anomaly.

### ISSUE THREAD

**Issue by 4l1fe** [vutran1710/PyrateLimiter#106]
Hey. I encountered interesting behavior of a limiter while parsing a resource that blocks my parser with **429 Too Many Requests**. After reading and analysing logs i found an anomaly and am sharing it with you.

## Parser threads code overview

My parser runs multiple threads and i want them to be limited with the second and minute rates.
```python
self.rate_limiter = Limiter(RequestRate(11, Duration.SECOND),
                            RequestRate(190, Duration.MINUTE)
)
```

When a thread makes a request it tries to bypass a context manager
```python
def parse(self):
    ...

    logger.msg(EventsEnum.data_get.value)
    with self.rate_limiter.ratelimit('all-targets', delay=True):
        resp = self.client.get(url)
```

All the threads are run in a loop
```python
def run_in_thread(self):
    while not self.stop_event.is_set():
        args = get_args()
    
        parse(args)  # `self.client.get(url)` is called here
```
## Parser running parameters

I ran `32` threads with limits above `11/s`, `190/m`

## Thread logs analysis

As you see threads log events `logger.msg(EventsEnum.data_get.value)`
Each event contains a timestamp and looks like this:
`{"event": "data.get", "timestamp": "2023-03-10T14:00:11.660406Z", "thread_name": "Consumer-1"}`

I read the log file and grouped log entries per second to check if it worked well as expected, BUT
```python
import pandas as pd

df = pd.read_json('log.txt', lines=True)
df[df['event'] =='data.get'].resample('S', on='timestamp').size()
```

BUT what i see
```
timestamp
2023-03-10 14:00:10+00:00     1
2023-03-10 14:00:11+00:00    32  <-
2023-03-10 14:00:12+00:00    18  <-
2023-03-10 14:00:13+00:00    11
2023-03-10 14:00:14+00:00     9
2023-03-10 14:00:15+00:00    10
2023-03-10 14:00:16+00:00    11
2023-03-10 14:00:17+00:00     3
Freq: S, dtype: int64
```
## Anomaly

I see the values per second which look abnormal `32, 18`. I expected 30 threads to request with a rate around ~11

At the same time, all the subsequential groups are within the correct rate `11`

## Question

I think `32` is a normal state as it was an initial attempt to acquire a bucket by all the threads, 30 consumers + 2 producers.

But why the next second contains `18` event? It is the second iteration of attempting to ack the bucket. I guess it has to be around ~11 events.
Do you think it's wrong statistics or correct?

**Comment by vutran1710** [comment]
what type of Bucket are u using here?

**Comment by 4l1fe** [comment]
> what type of Bucket are u using here?

Default class. You can see the limiter constructor in **Parser threads code overview**

**Comment by vutran1710** [comment]
Sorry I have been quite busy recently, Ill take a look at it when available.

**Comment by vutran1710** [comment]
Close as it is now oudated
