### ISSUE TITLE
redis-py-cluster has been decommissioned 

### ISSUE THREAD

**Issue by petroslamb** [vutran1710/PyrateLimiter#109]
Hi, very nice library, thanks for the good work.

It seems like the package [EOL](https://github.com/Grokzen/redis-py-cluster#redis-py-cluster-eol). The last version does not support redis > 4.0.0, so this makes cluster mode unusable right now for latest redis-py versions.

**Comment by vutran1710** [comment]
This will be dealt with in the next major release

**Comment by vutran1710** [comment]
Resolved in the new major version (v3.0.0)
