### ISSUE TITLE
DynamoDB Buckets

### ISSUE THREAD

**Issue by estahn** [vutran1710/PyrateLimiter#113]
We would like to use DynamoDB for persistence. I'd like to contribute the feature. Is the bucket design the same in v3?

**Comment by vutran1710** [comment]
for V3, please refer to https://github.com/vutran1710/PyrateLimiter/blob/pyrate-limiter-v3/pyrate_limiter/abstracts/bucket.py#L15

If you are in urgent need, then you can contribute to v2

V3 is expected to be released somewhere around Oct 23, so its gonna be a while until then.

**Comment by vutran1710** [comment]
If Dynanmo is integrated to PyrateLimiter v2, I will port it to v3 as well

**Comment by estahn** [comment]
Well, that is a quick response :)

I can definitely contribute to v2 and v3.

**Comment by vutran1710** [comment]
V3 is out. You can either...
- Implement your own bucket, or
- Make PR for contribution, or
- Wait until I find the time to do it

**Comment by hleong25** [comment]
Curious to see if there is any progress with this feature.

**Comment by estahn** [comment]
@hleong25 I have not a chance to work on this as priorities have shifted. I'm happy for you to take this on.
