### ISSUE TITLE
coroutine 'Redis.execute_command' was never awaited

### ISSUE THREAD

**Issue by snimshchikov** [vutran1710/PyrateLimiter#121]
I am testing version 3 with redis backend and I keep getting `.../pyrate_limiter/abstracts/bucket.py:174: RuntimeWarning: coroutine 'Redis.execute_command' was never awaited` on startup

Huge thanks for releasing v3

**Comment by vutran1710** [comment]
> I am testing version 3 with redis backend and I keep getting `.../pyrate_limiter/abstracts/bucket.py:174: RuntimeWarning: coroutine 'Redis.execute_command' was never awaited` on startup
> 
> 
> 
> Huge thanks for releasing v3

can you share bit of the code?

**Comment by vutran1710** [comment]
oh i got it - thats actually alright. the line 174 is just testing whether we are using async or not and its not needed to be executed. you can safely ignore the warning unless its crashing your app.

**Comment by vutran1710** [comment]
the line's warning should have been suppressed. ill update it soon

**Comment by snimshchikov** [comment]
thank you!
