### ISSUE TITLE
ImportError: cannot import name 'FileLockSQLiteBucket'

### ISSUE THREAD

**Issue by raratiru** [vutran1710/PyrateLimiter#129]
Not sure if related to #128 

I have this simple code that answers the solved issue #67 : 
(Rate limit multiple processes that are running simultaneously)

```python
from pyrate_limiter import Duration, FileLockSQLiteBucket, Limiter, RequestRate


global_limiter = Limiter(
    RequestRate(1, Duration.SECOND),     
    bucket_class=FileLockSQLiteBucket,
)
```

However, this does not work after updating to version 3:

`ImportError: cannot import name 'FileLockSQLiteBucket' from 'pyrate_limiter'`

I am not sure that the new docs address this issue as simple as that.

Could you please advice?

**Comment by vutran1710** [comment]
FileLockSQLite is not yet provide for v3.

For now you should use different file for each bucket

**Comment by raratiru** [comment]
Will `FileLockSQLite`  be provided in future releases?

**Comment by vutran1710** [comment]
I thought you can install it as peer-dependency?

**Comment by vutran1710** [comment]
> Will `FileLockSQLite`  be provided in future releases?

Ah sure I will add it to v3 sure. Just having too much in my plate lately

**Comment by raratiru** [comment]
OK, no hurry! 
Just wanted to confirm, thank you!
