### ISSUE TITLE
3.x sqlite seems broken?

### ISSUE THREAD

**Issue by indigoviolet** [vutran1710/PyrateLimiter#132]
The docs for how to get a SQLite bucket are inadequate (it seems like you have to set up the bucket table.. ) also there is a bug:

```
    if isawaitable(clock.now()) or isawaitable(bucket.leak(0)):
.venv/lib/python3.11/site-packages/pyrate_limiter/buckets/sqlite_bucket.py:122: in leak
    self.conn.execute(query)
E   sqlite3.OperationalError: near "ORDER": syntax error
```

You might want to warn users that 3.x is not ready for use (based on how much stuff is missing in #118)

**Comment by vutran1710** [comment]
tks, ill investigate this erro

**Comment by netanelrevah** [comment]
#141

**Comment by vutran1710** [comment]
Fixed by @netanelrevah
