### ISSUE TITLE
Is v3.6 backwards compatible, due to the psycopg2/3 upgrade?

### ISSUE THREAD

**Issue by petroslamb** [vutran1710/PyrateLimiter#170]
Hello, 

I noticed in the release notes that v3.6 switched to psycopg3, at least for the PostgresBucket. Is everything else still backwards compatible? 

PS: I believe it is as the release does not mention any breaking changes, in which case feel free to close this.

**Comment by vutran1710** [comment]
the API is still the same, so if the psycopg version change does not cause you trouble, then everything should be fine.

**Comment by petroslamb** [comment]
Thanks for the quick answer @vutran1710, 

Just to make sure I got this, if I install pyrate-limiter without the extras and keep my version of psycopg2 in my project, am i going to be able to use the library (excluding the PostgresBucket of course), or is any of the imports going to complain you think?

**Comment by vutran1710** [comment]
if you can't, I'll bring down the whole project myself and stop coding for good.

> Thanks for the quick answer @vutran1710,
> 
> Just to make sure I got this, if I install pyrate-limiter without the extras and keep my version of psycopg2 in my project, am i going to be able to use the library (excluding the PostgresBucket of course), or is any of the imports going to complain you think?

**Comment by petroslamb** [comment]
Great thanks, no i wouldn't want that!
