### ISSUE TITLE
Feature request: Get time until bucket is no longer full

### ISSUE THREAD

**Issue by JWCook** [vutran1710/PyrateLimiter#19]
With per-second and per-minute rate limits, it often makes sense to just wait before sending the next request instead of canceling the request. Same for long-running batch jobs that can wait indefinitely. Currently I'm just handling this with a crude try-except-sleep loop.

For that use case, it would be very convenient if the `Limiter` class had a method to return the time remaining until a given bucket is no longer full. Alternatively, the time remaining could be set as an attribute on `BucketFullException`.

Would one of those two options be feasible?

**Comment by vutran1710** [comment]
That would be easy I think. Stay tuned!

**Comment by JWCook** [comment]
Sweet, thanks!

**Comment by vutran1710** [comment]
Solved: https://github.com/vutran1710/PyrateLimiter#bucketfullexception. 

Don't forget to upgrade to the latest version aka `2.1.0`.

Hope you find it useful!

> With per-second and per-minute rate limits, it often makes sense to just wait before sending the next request instead of canceling the request. Same for long-running batch jobs that can wait indefinitely. Currently I'm just handling this with a crude try-except-sleep loop.
> 
> For that use case, it would be very convenient if the `Limiter` class had a method to return the time remaining until a given bucket is no longer full. Alternatively, the time remaining could be set as an attribute on `BucketFullException`.
> 
> Would one of those two options be feasible?

**Comment by JWCook** [comment]
That looks perfect. Thanks for the quick update!
