### ISSUE TITLE
Feature request/PR proposal: Add async support

### ISSUE THREAD

**Issue by JWCook** [vutran1710/PyrateLimiter#21]
Hi again, I was wondering if you would be open to the idea of adding async support to pyrate-limiter? If so, I'd be willing to put together a PR for this.

The basic idea would be the same as [this unmerged PR](https://github.com/tomasbasham/ratelimit/pull/35) for the abandoned [ratelimit](https://github.com/tomasbasham/ratelimit) repo:
* Add a decorator that calls `Limiter.try_acquire()` before calling the wrapped function
* Inspect the wrapped function to see if it's a coroutine, and if so return an async function; otherwise return a normal function

I have use cases for both synchronous and asynchronous rate-limiting in different projects. I did take a look at [aiolimiter](https://github.com/mjpieters/aiolimiter), but it would be handy if I could use pyrate-limiter for both cases!

**Comment by vutran1710** [comment]
That would be nice I believe. PR is more than welcome!
