### ISSUE TITLE
Publish pyrate-limiter on conda-forge

### ISSUE THREAD

**Issue by JWCook** [vutran1710/PyrateLimiter#27]
I'd like to get pyrate-limiter published on [conda-forge](https://conda-forge.org/), so it can be available to install with the conda package manager. This will be needed in order to publish any other conda packages that depend on pyrate-limiter.

This process is mostly automated, and I'm willing to set this up. Let me know if you would prefer to do this yourself, or if you have any other thoughts on this.

**Comment by vutran1710** [comment]
Sure, just go right ahead.

I never used conda before so it would be great - and quicker if you could help out on this.

**Comment by JWCook** [comment]
Will do! I'll get that set up soon.

Conda is basically an alternative to pip and pypi that packages compiled binaries and other things in addition to python code, kind of similar to making RPM or DEB packages for specific Linux distros. It's popular among data scientists, for example, because a lot of the packages they use are heavy on the binary dependencies.

**Comment by JWCook** [comment]
Done! There's nothing you else you need to do at this point. From now on when you publish a new release to PyPI, it will automatically get built and published to conda-forge as well.

For reference:
* PR to add pyrate-limiter: https://github.com/conda-forge/staged-recipes/pull/14714#event-4646131248
* Auto-generated feedstock (build config): https://github.com/conda-forge/pyrate-limiter-feedstock
* Package info: https://anaconda.org/conda-forge/pyrate-limiter
