### ISSUE TITLE
Should the basic_algorithm submodule be gotten rid of?

### ISSUE THREAD

**Issue by Jude188** [vutran1710/PyrateLimiter#3]
I've been looking at this project (which seems absolutely great by the way!!) and it occurs to me that the basic_algorithm submodule is basically just duplicate code which uses a list rather than the LocalBucket class? Is this something that should really be gotten rid of to remove duplicate code?

I'm also looking at add thread safety and potentially async support! 

Furthermore, since https://github.com/tomasbasham/ratelimit seems to have been abandoned... do you think that it makes sense for this project to support rate limiting both client requests and server side compute? We could add function decorators similar to the ratelimit project linked which used a rate limiting algorithm to limit API requests!

I feel like Python needs a good rate limiting package for both servers and clients and with a name like PyrateLimiter I feel like this has amazing potential! :P

**Comment by vutran1710** [comment]
Thx for your interest. I had the same problem when looking for a decent python rate-limiting module.
Regarding the duplication, I think you are right. 
When I first wrote this, i was asked to explain the algorithm to my supervisor so I had to put it in the repo. For now, I guess we can remove it and place it in some gist for reference in the document.
