### ISSUE TITLE
Temporary python3.6 support?

### ISSUE THREAD

**Issue by JWCook** [vutran1710/PyrateLimiter#31]
I have one library that uses pyrate-limiter and needs to support python3.6 for a bit longer (until it [goes EOL in December](https://endoflife.date/python)). I tested pyrate-limiter on 3.6.12 and it works fine, and doesn't appear to use any language features specific to 3.7+ yet.

Currently the package metadata prevents it from being installed on 3.6, though. Would you be willing to make just one release that supports 3.6? I believe all that's needed is to change this setting in `pyproject.toml`:
```toml
[tool.poetry.dependencies]
python = "^3.6"
```

No need for continued support, though; it can be bumped back to 3.7+ immediately afterward.

**Comment by vutran1710** [comment]
Seems no problem to me. I'll handle that.

**Comment by JWCook** [comment]
Awesome, thank you!

**Comment by JWCook** [comment]
Confirmed that `2.3.3` is installable under python3.6 now.

Thanks for the quick response!
