### ISSUE TITLE
Interrupt/cancel enqueued tasks

### ISSUE THREAD

**Issue by alkasm** [vutran1710/PyrateLimiter#34]
It would be great if there was a way to interrupt and/or cancel the enqueued tasks. One method to accomplish this might be to have a `threading.Event` object which you can `wait(timeout)` on, instead of `time.sleep(timeout)`.

**Comment by vutran1710** [comment]
Hi, tks for request. 
I'll see what I can do.

**Comment by vutran1710** [comment]
Issue being too old.
