### ISSUE TITLE
Feature request/proposal: SQLite support

### ISSUE THREAD

**Issue by JWCook** [vutran1710/PyrateLimiter#37]
I think a SQLite-backed bucket would be a nice addition to this library, as it fits a gap between the current memory and Redis options. I don't need this immediately, but will in the future. Here's my use case:

I have a library that currently uses pyrate-limiter, and at some point I'll add a CLI tool that wraps that library. An in-memory bucket won't work because it will only stay in memory for the duration of a single CLI invocation. Redis is a good option, but most users won't have Redis set up on their local machine.

I think SQLite would be a good fit here, because it's simple, fast, and part of the standard library. I would be willing to work on this. If needed, async support could be added later on via [aiosqlite](https://github.com/omnilib/aiosqlite).

What do you think?

**Comment by vutran1710** [comment]
Sounds reasonable to me. I'll be helping if needed.
