### ISSUE TITLE
Seeing very high seconds remaining

### ISSUE THREAD

**Issue by dvf** [vutran1710/PyrateLimiter#48]
Firstly, this library is awesome. But I'm seeing incorrect (very high seconds remaining). 
I'm not sure what the best way is to debug this. 

```python
from django_redis import get_redis_connection
from pyrate_limiter import RequestRate, Duration, Limiter, RedisBucket, MemoryListBucket


r = get_redis_connection("default")

bucket_kwargs = {
    "bucket_name": "my-throttles",
    "redis_pool": r.connection_pool
}

rate = RequestRate(2, 10 * Duration.SECOND)

limiter = Limiter(rate, bucket_class=RedisBucket, bucket_kwargs=bucket_kwargs)

try:
    limiter.try_acquire("200019946008641531")
except BucketFullException as e:
    print(e.meta_info)

# {'error': 'Bucket for 200019946008641531 with Rate 2/10 is already full', 'identity': '200019946008641531', 'rate': '2/10', 'remaining_time': 82992.52364823502}
```

Any help would be appreciated.

**Comment by dvf** [comment]
I've just tried it with `MemoryListBucket` locally and it seems fine, although that's not running in production.

I'll try downgrade and see if that makes a difference. Thanks for the fast responses.

**Comment by dvf** [comment]
I've been testing it for a few hours on `2.3.4` and there's no problem. Seems like a regression with the new version.

**Comment by niksite** [comment]
Still seeing this issue (delay_time=1545328.1461257488) on the current version of lib.
