### ISSUE TITLE
How to disable limiter in testing?

### ISSUE THREAD

**Issue by Merinorus** [vutran1710/PyrateLimiter#52]
Hello,
I'm using this limiter as a decorator (but I could use other methods I guess):

```python
from pyrate_limiter import Limiter, RequestRate, Duration
limiter = Limiter(RequestRate(10, Duration.HOUR))

@limiter.ratelimit("send_message", delay=False)
def send_msg(msg):
    ...
```

This works well and I can test it raises in an exception after 10 tries with pytest.
But if I use this function on more time in my tests it fails obviously.
What are the good practices to disable this limitation in tests?
Thank you!

**Comment by vutran1710** [comment]
no further comment
