### ISSUE TITLE
Development installation is not described

### ISSUE THREAD

**Issue by insspb** [vutran1710/PyrateLimiter#54]
As development installation is not described I tried with regular
```
pip install -e .
```

Claims `setuptools` not in requirements. 

```
[PyrateLimiter] insspb@insspb-kubuntu ~/git/PyrateLimiter (master)$ pip install -e .
Obtaining file:///home/insspb/git/PyrateLimiter
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: pyrate-limiter
  Running setup.py develop for pyrate-limiter
    ERROR: Command errored out with exit status 1:
     command: /home/insspb/.venvs/PyrateLimiter/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/insspb/git/PyrateLimiter/setup.py'"'"'; __file__='"'"'/home/insspb/git/PyrateLimiter/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/insspb/git/PyrateLimiter/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/insspb/.venvs/PyrateLimiter/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/insspb/git/PyrateLimiter/setup.py'"'"'; __file__='"'"'/home/insspb/git/PyrateLimiter/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
[PyrateLimiter] insspb@insspb-kubuntu ~/git/PyrateLimiter (master)$ 
```

But it is there:

```
[PyrateLimiter] insspb@insspb-kubuntu ~/git/PyrateLimiter (master)$ pip install setuptools
Requirement already satisfied: setuptools in /home/insspb/.venvs/PyrateLimiter/lib/python3.9/site-packages (58.2.0)
```

I was success with

```
pip install poetry
poetry install
```

But it is too hard for me :rofl: Need to be documented/fixed.

**Comment by vutran1710** [comment]
🤣 lol you are right! Updating!

**Comment by insspb** [comment]
To clarify. This should be fixed, because while this exist this will not allow to include dev versions to stage environments for tests. I am not working with poetry and do not have time to look at.

**Comment by vutran1710** [comment]
> To clarify. This should be fixed, because while this exist this will not allow to include dev versions to stage environments for tests. I am not working with poetry and do not have time to look at.

Here you are:
https://github.com/vutran1710/PyrateLimiter/blob/master/README.md#development

**Comment by insspb** [comment]
@vutran1710 You decided only to add documentation, not to fix a problem. Up to you. But in this case I recommend you to include information how to add current master/not released branch to classic requirements.txt. Users will not use poetry just for your project.

Classic 
`-e git+https://github.com/vutran1710/PyrateLimiter.git#egg` will not work in your case. As editable installation without poetry not working. (user will face same error as described).

But it is possible to install as zip, by just addition of: `https://github.com/vutran1710/PyrateLimiter/archive/refs/heads/master.zip` without any modifies.
