### ISSUE TITLE
pypi releases does not have coresponding git tags in repository.

### ISSUE THREAD

**Issue by slashbeast** [vutran1710/PyrateLimiter#62]
Hi,

Seems like the pypi releases of pyrate-limiter does not have the version tags reflected in this repository. Would that be possible for you to add those?

**Comment by vutran1710** [comment]
Sure, Ill take a look at it in the next few days

**Comment by vutran1710** [comment]
@slashbeast  Added

**Comment by slashbeast** [comment]
Thank you!
