### ISSUE TITLE
Set up Sphinx documentation builds and publish to readthedocs.io

### ISSUE THREAD

**Issue by JWCook** [vutran1710/PyrateLimiter#69]
Since this library appears to be reasonably popular now, I think it deserves its own documentation site!

For now, this could just consist of the Readme contents plus some auto-generated API docs with sphinx-autodoc. Later on, as more features and docs are added, it might be beneficial to split up the user guide into multiple pages instead of putting everything in the Readme. You can decide how you want to organize it, though.

I would be happy to set up the Sphinx build and a site on readthedocs.io. Just started a project [here](https://readthedocs.org/projects/pyrate-limiter/). All I would need from you is to add a webhook to this repo that will trigger doc builds. There are two ways to do that:
* Make an account on readthedocs, link your GitHub account, and I can add you to the project. Then go to Admin -> Integrations and click Resync webhook
* Manually add a new webook on this repo for this URL: https://readthedocs.org/api/v2/webhook/pyrate-limiter/196818/
    * The webhook needs to be triggered by these events: pushes, branch/tag creation, branch/tag deletion, and pull requests. Exact conditions for building are configured on readthedocs.
    * Accepts `application/json`

More details here: https://docs.readthedocs.io/en/stable/integrations.html

**Comment by vutran1710** [comment]
Be my guest!
Personally I really like request-rate-limiter doc. Its yours, isnt't?

**Comment by JWCook** [comment]
Thanks! Yes, I started [requests-ratelimiter](https://github.com/JWCook/requests-ratelimiter) based on some of the ideas we talked about in #35. If you have any feedback on that I'd appreciate it.

I can make the pyrate-limiter docs look pretty much the same as https://requests-ratelimiter.readthedocs.io: one page for the user guide, and one page for API reference. And you can see an example of a larger documentation site (built with mostly the same tools) here: https://requests-cache.readthedocs.io. But hopefully this library won't get as complicated as that one.
