### ISSUE TITLE
Redis cache doesn't expire

### ISSUE THREAD

**Issue by maximepeabody** [vutran1710/PyrateLimiter#74]
It seems that the data being stored when using redis doesn't expire. For rate limiting, there's no need to store the data for longer than the rate denominator (i.g, @ 500 requests per hour, you can expire the cache after 1 hour if no additional request comes in). 

We are using this, and it's causing our cache to blow up as more and more users use our app.

**Comment by vutran1710** [comment]
good point. I'll look into the problem soon.

**Comment by vutran1710** [comment]
Fixed in #82
