### ISSUE TITLE
Support sub second intervals

### ISSUE THREAD

**Issue by judahrand** [vutran1710/PyrateLimiter#75]
I've run into an issue with this package where I'm unable to respect NGINX rate limits because they are automatically applied on a per millisecond basis: https://www.nginx.com/blog/rate-limiting-nginx/#Configuring-Basic-Rate-Limiting.

This means even if I set the limit 'correctly' per second PyrateLimiter won't respect the millisecond latency. Therefore, PyrateLimiter should support millisecond intervals.

**Comment by judahrand** [comment]
It looks like this does already work as you can pass a `float` to the `interval` parameter. However, the type hinting doesn't match.

**Comment by petroslamb** [comment]
Correct me if I am wrong, but the redis  backend complained with a non integer interval on v2.10.0.

**Comment by vutran1710** [comment]
> Correct me if I am wrong, but the redis  backend complained with a non integer interval on v2.10.0.
> 
> 
> 
> 

Yes
