### ISSUE TITLE
Publish the pure-python wheel

### ISSUE THREAD

**Issue by edgarrmondragon** [vutran1710/PyrateLimiter#85]
Attempting to install an application that depends on this library with the restriction to only use binary wheels (i.e. `pip install --only-binary=":all"`) fails because [there isn't a wheel available on PyPI](https://pypi.org/project/pyrate-limiter/#files):

```
ERROR: Could not find a version that satisfies the requirement pyrate-limiter<3.0.0,>=2.8.3 (from tap-stackexchange) (from versions: 0.1.0, 0.1.1, 1.0.0, 1.1.0, 2.1.0, 2.2.0)
ERROR: No matching distribution found for pyrate-limiter<3.0.0,>=2.8.3
```

The solution is as simple as change this line

https://github.com/vutran1710/PyrateLimiter/blob/cbdd3c6544d50319f183c86dcdaa20803cbfa878/.github/workflows/poetry-package.yml#L83

to

```diff
-          poetry build -f sdist 
+          poetry build
```

so that `poetry build` pushes both the sdist and wheel to PyPI.

Note: There's a way to skip the wheel check just for this library with `pip install --only-binary=":all" --no-binary="pyrate-limiter"`, but it'd still be nice not to have to do that 🙂 .

**Comment by vutran1710** [comment]
Oh ok, thanks for the help. I'm going to have it fixed
