### ISSUE TITLE
API standardisation 

### ISSUE THREAD

**Issue by Jude188** [vutran1710/PyrateLimiter#9]
Having been reading a bit about various rate limiting implementations it seems to be like perhaps this project should take inspiration from some other well established rate limiter?

Google Guava's ratelimiter jumps out at me as a good one to base the interface around?

Here are some links with more info:
  - https://dzone.com/articles/detailed-explanation-of-guava-ratelimiters-throttl
  - https://hechao.li/2018/06/27/Rate-Limiter-Part2/

Do let me know if you think some small adjustments such as standardizing on an `.aquire()` interface for the Limiters makes sense.

**Comment by vutran1710** [comment]
`Google Guava` style is something that I'm reluctant to adapt. To my taste, it introduces unnecessary `fancy-terms` like `smooth bursty/smooth warm up` that makes the concept becomes harder to grasp, especially for people who are new to the throttling strategies.

So, I agree standardization totally makes sense, but lets keep it simple, extensible and easy to understand.

I'm also looking for inspiration from some node-packages. I think they have some nice API documents, eg https://www.npmjs.com/package/bottleneck

**Comment by Jude188** [comment]
That makes sense and I think that your approach so far achieves just that.

I do have a small concern around the current limitations of the concept of a Bucket, however. For window based (rather than bucket orientated)  algorithms as mentioned in (this link)[https://hechao.li/2018/06/25/Rate-Limiter-Part1/] , a 'Mapping' seems more appropriate as a 'window' maps quite nicely to a key and it's count as a value.

I'm not sure if this should be a separate concept? Perhaps we'd have:

  * AbstractBucket
  * AbstractBucketLimiter
  * AbstractWindow
  * AbstractWindowLimiter

**Comment by vutran1710** [comment]
Currently, while I think we can just refactor the code to what they described in the blog, I also have some concerns, like, I don't see the point of using something like `Fixed Window Counter` - which basically a flawed strategy anyway.
I will think more about it and reply soon.

**Comment by vutran1710** [comment]
From my understanding, having 4 abstract classes like you proposed is not really necessary.
The algorithms mentioned in the article basically fall into 2 categories:

+ Defining `average processing-rate`,  aka the `requests/time` rate.
The `Token Bucket` and `Sliding Window Log` are quite the same thing from my point of view. What differs is just where they keep the time-logs.

+ Defining `atomic processing-rate`, aka `single-request/time` rate.
The `Leaky Bucket` falls into this category.

The way I see it is, we can even consider the Leaky-Bucket a special case of the first `average-rate` method, where the `average processing rate = 1 request/time`. The time-log has to be written down somewhere, and my solution is to directly append it to the item to be processed - which seems very generic and applicable to other strategies as well.

So I think, for both categories, a single queue-like object is enough to reflect all above cases. Maybe I can go even further by writing one single `BucketLimiter` class only that takes the `average processing-rate` as single parameter for initialization.

Regarding other methods that are mentioned in the articles, Im not sure they are even worth considering...:
+ The `Fixed Window Counter` is just flawed - as the cross-window rate can exceed the expected processing-rate (200% the  defined processing-rate at maximum).
+ The `Sliding Window` with weighted counts is just, well, over-complicating the problem.

Plus, I also notice that some of my implementations are not entirely correct and needs fixing too.

What I really look forwards to are useful enhancements, like decorators, clustering etc.

**Comment by Jude188** [comment]
That seems like a fair analysis. And you're probably right that it's worth adding things like the a decorator etc. before considering additional algorithms anyway. I'm happy to take a look at a decorator implementation when I get the chance in the coming days.

I did also have a quick look at your RedisBucket implementation and was wondering how we would make it safe for multiple clients to use the same Bucket to rate limit. I assume this is part of the point of using an external Bucket and certainly an extremely interesting use-case? For example if I were pulling data from a single API in a multi-tenanted scenario using a single set of credentials it would be nice to be able to have a global ratelimit across clients.

If that's the case then it becomes important that any change or check to the Bucket is atomic. In Redis' case I believe that a lock can be obtained but I wonder if this is something that there should also be a standard interface for?

**Comment by Jude188** [comment]
Some other resources suggesting that perhaps Token Bucket isn't the be all and end all:
 * https://engineering.classdojo.com/blog/2015/02/06/rolling-rate-limiter/
 * https://medium.com/figma-design/an-alternative-approach-to-rate-limiting-f8a06cf7c94c

**Comment by vutran1710** [comment]
no active
