### ISSUE TITLE
Build on pypi is not on github?

### ISSUE THREAD

**Issue by farchord** [vutran1710/PyrateLimiter#91]
Hello!

I'm working on building this library for Fedora, and I noticed that 2.8.5 is on pypi but is not on this github.

Is there any plans on making it available on github too? Asking as that would make automated rebuilds much simpler on fedora's end.

Thanks!

**Comment by musicinmybrain** [comment]
See also https://github.com/vutran1710/PyrateLimiter/issues/62.

**Comment by vutran1710** [comment]
> Hello!
> 
> I'm working on building this library for Fedora, and I noticed that 2.8.5 is on pypi but is not on this github.
> 
> Is there any plans on making it available on github too? Asking as that would make automated rebuilds much simpler on fedora's end.
> 
> Thanks!

Yes, this is the project's top priority now. Yet currently i'm pretty busy so it will take a few days

**Comment by mgorny** [comment]
Ping. There's 2.9.0 out now and still the same problem.

**Comment by mgorny** [comment]
Alternatively, could you include tests and doc sources in sdist archives, so that they would be useful for us?

**Comment by vutran1710** [comment]
@mgorny @farchord  ref to https://github.com/vutran1710/PyrateLimiter/releases/tag/v2.9.1

**Comment by musicinmybrain** [comment]
> Alternatively, could you include tests and doc sources in sdist archives, so that they would be useful for us?

Looks like you did this *and* started tagging releases, which is awesome! Thank you.

**Comment by mgorny** [comment]
Thanks a lot!
